[package]
name = "native-glutin"
version = "0.0.1"
authors = ["Benjamin Wasty <benjamin.wasty@cginternals.com>", "Stefan Buschmann <stefan.buschmann@cginternals.com>"]
edition = "2018"

[dependencies]
glutin = "0.19.0"
gl = "0.12.0"
cgmath = "0.17.0"
image = "0.21.1"
yage = { path = "../../" }
